name: Unlock-NetEaseMusic

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chrome & Chromedriver
        run: |
          echo "Installing Google Chrome and Chromedriver..."
          choco install googlechrome -y
          choco install chromedriver -y --force
          echo "✅ Chrome & Chromedriver installed successfully."

      - name: Debug Chrome and Chromedriver
        shell: pwsh # 强制使用 PowerShell
        run: |
          echo "Checking Chrome version..."
          if (Test-Path "C:\Program Files\Google\Chrome\Application\chrome.exe") {
              & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version
          } else {
              echo "❌ Chrome not found!"
          }

          echo "Checking Chromedriver version..."
          if (Get-Command chromedriver -ErrorAction SilentlyContinue) {
              chromedriver --version
          } else {
              echo "❌ Chromedriver not found!"
          }

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unlock script
        env:
          MUSIC_U: ${{ secrets.MUSIC_U }}
          PYTHONIOENCODING: utf-8
          PYTHONLEGACYWINDOWSSTDIO: utf-8
        run: python auto_login.py
